import { Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <link rel="preload" href="/fonts/my-font.woff2" as="font" type="font/woff2" crossorigin="anonymous" /> */}

      <body
        className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
